### ISSUE TITLE
Can not send video

### ISSUE THREAD

**Issue by axixu** [open-wa/wa-automate-deploy-heroku#5] opened 2021-01-04 09:15 UTC
Hi, 

Hi, I have successfully install wa-automate on heroku. unfortunately, I still can not send video from easyAPI. I use API sendFile, sendFileFromUrl, sendImage they same sent as file of MP4 not video.

this is my try in swagger UI for API sendFileFromUrl

```javascript
{
  "args": {
    "to": "xxxxxxxxxx@c.us",
    "url": "https://i.giphy.com/media/oYtVHSxngR3lC/200w.mp4",
    "filename": "string",
    "caption": "Hello World!",
    "quotedMsgId": "",
    "requestConfig": "any",
    "waitForId": "false",
    "ptt": "false",
    "withoutPreview": "false"
  }
}
```

before, I have tried wa-automate-node-js and same I still can not send video, even I've installed google-chrome and ffmpeg.

maybe next I want to try for docker version.

Thank you very much.

**Comment by smashah** [comment] 2021-03-02 19:51
@axixu I think the issue is that you're sending boolean values as strings, which then resolves all of them to `true`. You need to remove the `"` marks from the booleans and try again.

```javascript
{
  "args": {
    "to": "xxxxxxxxxx@c.us",
    "url": "https://i.giphy.com/media/oYtVHSxngR3lC/200w.mp4",
    "filename": "string",
    "caption": "Hello World!",
    "waitForId": false,
    "ptt": false,
    "withoutPreview": false
  }
}
```

**Comment by smashah** [comment] 2021-03-07 20:48
Please feel free to report back if the issue is still happening. Closing for now thanks

**Closed by smashah** 2021-03-07 20:48 UTC
